---
title: "microclimate"
author: "Dewi"
date: "26/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(lubridate)
library(leaflet)
library(plotly)
library(forcats)
library(tsibble)
```

```{r, message=FALSE, cache = TRUE}
readings <- read_csv("data/Microclimate_Sensor_Readings.csv")
locations <- read_csv("data/Microclimate_Sensor_Locations.csv")
```

```{r}
new_dat <- left_join(readings, locations, by = "site_id") %>%
  filter(type == "TPH.TEMP-EPA-1h") %>%
  mutate(local_time = ymd_hms(local_time))

new_dat <- new_dat %>%
  mutate(date = format(as.POSIXct(strptime(local_time,"%Y-%m-%d %H:%M",tz="")) ,format = "%Y-%m-%d"),
         month = month(local_time)) %>%
  mutate(season = ifelse(month == 12 | month == 1 | month == 2, "summer",
                         ifelse(month == 3 | month == 4 | month == 5, "autumn",
                                ifelse(month == 6 | month == 7 | month == 8, "winter",
                                       "spring"))))
  
```

## Visualisation 1

```{r}

color_index <- c(
      arc1046 = "navy",
      arc1047 = "tomato",
      arc1048 = "mediumpurple",
      arc1050 = "hotpink1",
      arc1045 = "turquoise3"
    )

p0 <- ggplot(new_dat,
       aes(x = local_time, 
           y = value,
           color = site_id)) +
  geom_line(size = 0.3,
            alpha = 0.8) +
  geom_smooth(method = "loess",
              se = FALSE,
              size = 0.8) +
  facet_grid(site_id ~ ., 
             # this code presents the facets in a  nice way
             labeller = labeller(site_id = label_wrap_gen(20))) +
  # this code mades the x axis a bit nicer to read
  scale_x_datetime(date_labels = "%d %b %Y", 
                   date_minor_breaks = "1 month") +
  labs(x = "Date Time") +
  scale_color_manual(values = color_index) +
  theme(legend.position = "none")

ggplotly(p0)
```

## Visualisation 2

```{r}

ggplot(new_dat,
       aes(x = local_time,
           y = value,
           group = date,
           colour = site_id)) +
  geom_line() +
  facet_wrap(~ site_id,
             labeller = labeller(site_id = label_wrap_gen(20))) +
  theme(legend.position = "none") +
  scale_color_manual(values = color_index)
```
```{r}
group_sensor <- new_dat %>%
  group_by(local_time) %>%
  summarise(med_tem = median(value, na.rm = TRUE)) %>%
  ungroup()

new_dat <- left_join(new_dat, group_sensor, by = "local_time")
```

```{r}
ts_new_dat <- as_tsibble(new_dat, index = local_time,
                         key = site_id) 

new_dat_miss <- fill_gaps(ts_new_dat, .full=TRUE) 


impute_temp <- left_join(new_dat_miss, group_sensor, by = "local_time")

imputed_temp <- impute_temp %>%
   mutate(value = ifelse(is.na(impute_temp$value),
                              impute_temp$med_tem.y, 
                              impute_temp$value))




ggplot(imputed_temp,
       aes(x = local_time,
           y = value,
           group = date,
           colour = site_id)) +
  geom_line() +
  facet_wrap(~ site_id,
             labeller = labeller(site_id = label_wrap_gen(20))) +
  theme(legend.position = "none") +
  scale_color_manual(values = color_index)

```

## Visualisation 3

```{r}

bp <- ggplot(imputed_temp,
       aes(y = value,
           x = fct_reorder(site_id, value, .fun = median, .desc = TRUE),
           colour = site_id)) +
  geom_boxplot() +
  theme(legend.position = "bottom") +
  scale_colour_manual(values = color_index) +
  theme(legend.position = "none")

ggplotly(bp)
```

## Visualisation 4

```{r boxplot}

get_plot <- function(df){
  plot <- ggplot(df,
       aes(y = value,
           x = fct_reorder(site_id, value),
           colour = site_id)) +
  geom_boxplot()+
  theme(legend.position = "bottom") +
  scale_colour_manual(values = color_index) +
  xlab("site ID") +
  ylab("temperature in Celcius") +
  theme(legend.position = "none") 
  ggplotly(plot)
}

summer <- imputed_temp %>%
  filter(season == "summer")

autumn <- imputed_temp %>%
  filter(season == "autumn")

winter <- imputed_temp %>%
  filter(season == "winter")

spring <- imputed_temp %>%
  filter(season == "spring")

summer_p <- get_plot(summer) #%>% layout(title = "Summer")
autumn_p <- get_plot(autumn) #%>% layout(title = "Autumn")
winter_p <- get_plot(winter) #%>% layout(title = "Winter")
spring_p <- get_plot(spring) #%>% layout(title = "Spring")

sp1<- subplot(summer_p, autumn_p, nrows = 2)
sp2<- subplot(winter_p, spring_p, nrows = 2)
  
winter_p
```

```{r}
# Compute the analysis of variance
res.aov <- aov(value ~ site_id, data = new_dat)
# Summary of the analysis
summary(res.aov)
```

```{r}
#melb_map <- read_rds(here::here("data/sensors.rds")) 



leaflet(locations) %>%
      addCircleMarkers(lng = 144.9641,
                 lat = -37.80052,
                 color = "navy",
                 label = "arc1046, 14.38C",
                 stroke = FALSE, fillOpacity = 0.7,
                 labelOptions = labelOptions(noHide = F, textOnly = FALSE),
                 radius = 14.38) %>%
      addCircleMarkers(lng = 144.9609,
                 lat = -37.80230,
                 color = "tomato",
                 stroke = FALSE, fillOpacity = 0.7,
                 label = "arc1047, 14.79C",
                 labelOptions = labelOptions(noHide = F, textOnly = FALSE),
                 radius = 14.79) %>%
      addCircleMarkers(lng = 144.9646,
                 lat = -37.80058,
                 color = "purple",
                 stroke = FALSE, fillOpacity = 0.7,
                 label = "arc1048, 14.22C",
                 labelOptions = labelOptions(noHide = F, textOnly = FALSE),
                 radius = 14.22) %>%
      addCircleMarkers(lng = 144.9651,
                 lat = -37.80063,
                 color = "magenta",
                 stroke = FALSE, fillOpacity = 0.7,
                 label = "arc1050, 14.12C",
                 labelOptions = labelOptions(noHide = F, textOnly = FALSE),
                 radius = 14.12) %>%
      addCircleMarkers(lng = 144.9665,
                 lat = -37.80079,
                 color = "turquoise",
                 stroke = FALSE, fillOpacity = 0.7,
                 label = "arc1045, 15.04C",
                 labelOptions = labelOptions(noHide = F, textOnly = FALSE),
                 radius = 15.04) %>%
      addProviderTiles("Stamen.Watercolor") 
  

```

```{r}
imputed_temp %>%
  group_by(site_id) %>%
  summarise(med = median(value))
```
```{r}
leaflet(locations) %>%
      addMarkers(lng = ~ longitude,
                 lat = ~ latitude) %>%
  addProviderTiles("Stamen.Watercolor") 
  
```

